import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Redux/provider";  

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fastrest QR",
  description: "Generated by create next app",
};

export default function RootLayout({params, children }) { 
  return (
    <html lang="tr" className="bg-hm-Light">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
